Repository mju-likelion/inception, pull requests merged in 2023-08, with the labels that each got.

#34 에러 모달 구현
  src/assets/images/ModalIconRoom.svg
  src/assets/images/ModalIconUser.svg
  src/assets/images/ModalIconWarning.svg
  src/component/@share/atom/ModalDimmed.tsx
  src/component/@share/atom/ModalIcon.tsx
  src/component/@share/molecules/ModalTitleBox.tsx
  src/component/@share/organisms/Modal.tsx
Labels: 리뷰 요청 - 개발 완료

#49 캘린더 click&drag
  src/component/@share/template/LoginMasterTemplate.tsx
  src/component/calendar/atom/GridItem.tsx
  src/component/calendar/molecules/Date.tsx
  src/component/calendar/organisms/calendar.tsx
Labels: 리뷰 요청 - 개발 완료

#56 로딩아이콘 구현
  src/component/@share/atom/LoadingIcon.tsx
  src/component/@share/atom/index.ts
Labels: 반려됨

#63 캘린더 포커스 이슈 해결
  src/component/calendar/atom/GridItem.tsx
  src/component/calendar/molecules/Date.tsx
  src/pages/Home.tsx
Labels: 리뷰 요청 - 개발 완료

#52 푸터(이메일) 및 결과 페이지(url,입장코드) 텍스트 복사 기능 구현
  package.json
  src/component/@share/atom/ButtonLarge.tsx
  src/component/@share/atom/ButtonSmall.tsx
  src/component/@share/molecules/Information.tsx
  src/component/@share/organisms/HelperModal.tsx
  src/component/@share/organisms/Modal.tsx
  src/component/@share/organisms/Toast.tsx
  src/component/@share/template/LoginCodeTemplate.tsx
  src/component/@share/template/LoginMasterTemplate.tsx
  src/component/@share/template/PossibleDateTemplate.tsx
  src/component/@share/template/PossibleTimeTemplate.tsx
  src/component/Footer/atoms/Mail.tsx
  src/component/Footer/data/OrganizationInfo.ts
  src/component/Footer/organism/Footer.tsx
  src/pages/CodeSubmitPage.tsx
  src/pages/Home.tsx
  src/pages/RedirectPage.tsx
  src/pages/ResultPage.tsx
  src/store/atoms/Toast/copyTypes.ts
  src/store/atoms/Toast/index.ts
  src/store/atoms/Toast/toastState.ts
  src/store/atoms/index.ts
  src/types/Toast.ts
  src/util/data/CopyTypeMessage.ts
  src/util/data/index.ts
  src/util/getToastMessage.ts
  src/util/index.ts
  yarn.lock
Labels: 리뷰 요청 - 개발 완료

#64 방 생성 api 연결
  src/component/calendar/organisms/Calendar.tsx
  src/pages/Home.tsx
  src/util/api/room.ts
  src/util/date.ts
  src/util/test/date.test.ts
Labels: 리뷰 요청 - 개발 완료

#68 가용 시간 등록 api 구현
  src/component/@share/template/LoginMasterTemplate.tsx
  src/pages/AppointmentStepPage.tsx
  src/store/atoms/Login/index.ts
  src/store/atoms/Login/state.ts
  src/util/api/index.ts
  src/util/api/user.ts
  src/util/getDatesAsc.ts
  src/util/index.ts
Labels: 리뷰 요청 - 개발 완료

#83 현재 달보다 이후의 달을 선택 가능할 때 캘린더가 안보이는 현상 수정
  src/component/@share/template/LoginMasterTemplate.tsx
  src/component/@share/template/PossibleDateTemplate.tsx
  src/component/calendar/organisms/Calendar.tsx
  src/pages/AppointmentStepPage.tsx
Labels: 리뷰 요청 - 개발 완료

#82 이슈 hotfix
  src/component/@share/atom/ButtonSmall.tsx
  src/component/@share/molecules/TitleBox.tsx
  src/component/@share/template/LoginMasterTemplate.tsx
  src/component/@share/template/PossibleDateTemplate.tsx
  src/component/@share/template/PossibleTimeTemplate.tsx
  src/pages/AppointmentStepPage.tsx
  src/pages/ResultPage.tsx
Labels: 리뷰 요청 - 개발 중

#87 로깅 연결 - centry
  package.json
  src/index.tsx
  yarn.lock
Labels: 리뷰 요청 - 개발 완료
