Repository mju-likelion/inception, pull requests merged in 2023-07, with the labels that each got.

#15 토스트 컴포넌트 UI 구현
  src/App.tsx
  src/assets/images/Error.svg
  src/assets/images/Success.svg
  src/component/@share/organisms/Toast.tsx
  src/component/@share/organisms/index.ts
  src/globalStyle/GlobalFont.ts
  src/globalStyle/InitStyle.ts
  src/hooks/useWindowResize.ts
  src/store/atoms/index.ts
  src/store/atoms/toastState.ts
  src/store/index.ts
Labels: 리뷰 요청 - 개발 완료

#20 Header, TabBar Web/Tablet 반응형 추가
  src/App.tsx
  src/component/@share/atom/Helper.tsx
  src/component/@share/organisms/Header.tsx
  src/component/@share/organisms/TabBar.tsx
  src/store/atoms/index.ts
  src/store/atoms/tabState.ts
Labels: 리뷰 요청 - 개발 완료

#17 공통컴포넌트 back arrow btn 구현
  src/component/@share/atom/BackButton.tsx
Labels: 리뷰 요청 - 개발 완료

#18 공통컴포넌트 next arrow btn 구현
  src/component/@share/atom/NextButton.tsx
Labels: 리뷰 요청 - 개발 완료

#19 타임 블럭 구현
  package.json
  src/component/@share/atom/index.ts
  src/component/timeBlock/atoms/Dates.tsx
  src/component/timeBlock/atoms/DuringDate.tsx
  src/component/timeBlock/atoms/ErrorMessage.tsx
  src/component/timeBlock/atoms/Time.tsx
  src/component/timeBlock/atoms/TimeBlock.tsx
  src/component/timeBlock/atoms/index.ts
  src/component/timeBlock/molecules/DateList.tsx
  src/component/timeBlock/molecules/SelectAllButton.tsx
  src/component/timeBlock/molecules/SelectDate.tsx
  src/component/timeBlock/molecules/TimeBlockGroup.tsx
  src/component/timeBlock/molecules/TimeList.tsx
  src/component/timeBlock/molecules/index.ts
  src/component/timeBlock/organisms/TimeBlockHeader.tsx
  src/component/timeBlock/organisms/index.ts
  src/component/timeBlock/template/TimeBox.tsx
  src/component/timeBlock/template/index.ts
  src/store/atoms/dateList.ts
  src/store/atoms/index.ts
  src/store/atoms/timeList.ts
  src/store/atoms/timeTable.ts
  src/util/getDateTypeToString.ts
  src/util/index.ts
  src/util/pagination.ts
  yarn.lock
Labels: 리뷰 요청 - 개발 완료

#4 캘린더 템플릿 제작 ☆★☆★ 리뷰 좀 해줘 ★☆★☆
  src/component/calendar/atom/Count.tsx
  src/component/calendar/atom/GridItem.tsx
  src/component/calendar/atom/index.ts
  src/component/calendar/molecules/CalendarHeader.tsx
  src/component/calendar/molecules/Date.tsx
  src/component/calendar/molecules/DateHeader.tsx
  src/component/calendar/molecules/index.ts
  src/component/calendar/organisms/calendar.tsx
  src/pages/CalendarTest.tsx
  src/types/Calendar.ts
  src/types/index.ts
  src/util/date.ts
  src/util/test/date.test.ts
Labels: 리뷰 요청 - 개발 완료

#25 가용시간 선택 페이지
  src/component/@share/molecules/Information.tsx
  src/component/index.ts
  src/component/timeBlock/index.ts
  src/component/timeBlock/molecules/TimeBlockGroup.tsx
  src/component/timeBlock/template/TimeBox.tsx
  src/pages/PossibleTimePage.tsx
  src/pages/index.tsx
Labels: 리뷰 요청 - 개발 완료

#30 KeyPage 최종 결과 페이지 구현
  src/component/@share/molecules/Information.tsx
  src/component/calendar/organisms/calendar.tsx
  src/pages/PossibleTimePage.tsx
  src/pages/Result.tsx
  src/pages/index.tsx
Labels: 리뷰 요청 - 개발 완료

#21 KeyPage 코드입력 및 첫 유저(마스터)가 결과보기를 클릭했을 경우
  src/component/@share/atom/Back.tsx
  src/component/@share/atom/Input.tsx
  src/component/@share/atom/Next.tsx
  src/component/@share/template/CodeSubmitTemplate.tsx
  src/pages/PossibleTimePage.tsx
Labels: 리뷰 요청 - 개발 완료

#26 리다이렉트페이지(404,500)
  _redirects
  src/assets/images/ErrorState404.svg
  src/assets/images/ErrorState500.svg
  src/assets/images/RedirectDoorInDesktop.svg
  src/assets/images/RedirectDoorInTablet.svg
  src/component/ErrorPage/atoms/RedirectPage.tsx
  src/component/ErrorPage/atoms/index.ts
  src/component/ErrorPage/data/ErrorAlertText.ts
  src/component/ErrorPage/data/index.ts
  src/pages/index.tsx
Labels: 리뷰 요청 - 개발 완료

#28 날짜 선택 페이지
  src/component/@share/organisms/TabBar.tsx
  src/component/TimePicker/molecules/SelectionList.tsx
  src/component/TimePicker/molecules/TimeSelectionBox.tsx
  src/component/TimePicker/organisms/TimePicker.tsx
  src/component/calendar/organisms/calendar.tsx
  src/pages/SelectDate.tsx
  src/pages/index.tsx
  src/store/atoms/TimePicker/selectedEndTime.ts
  src/store/atoms/TimePicker/selectedStartTime.ts
  src/types/index.ts
  src/util/date.ts
Labels: 리뷰 요청 - 개발 완료

#29 KeyPage 메인 페이지(마스터 등장 페이지) 구현
  src/assets/images/TimePickerBar.svg
  src/component/@share/index.ts
  src/component/TimePicker/data/TimeList.ts
  src/component/TimePicker/organisms/TimePicker.tsx
  src/component/index.ts
  src/pages/Home.tsx
  src/types/TimePicker.ts
Labels: 리뷰 요청 - 개발 완료

#32 HelperModal 페이지별 연결
  src/component/@share/atom/ButtonLarge.tsx
  src/component/@share/atom/Helper.tsx
  src/component/@share/molecules/ProgressBarModal.tsx
  src/component/@share/organisms/Header.tsx
  src/component/@share/organisms/HelperModal.tsx
Labels: 리뷰 요청 - 개발 완료

#33 결과 캘린더 컴포넌트
  src/component/calendar/atom/Count.tsx
  src/component/calendar/atom/GridItem.tsx
  src/component/calendar/data/index.ts
  src/component/calendar/data/result.ts
  src/component/calendar/molecules/Date.tsx
  src/component/calendar/organisms/calendar.tsx
  src/hooks/calendar.ts
  src/hooks/index.ts
  src/types/Calendar.ts
  src/util/date.ts
Labels: 리뷰 요청 - 개발 중

#40 iOS chrome(구글) Footer Email Button 디자인 이슈 해결
  src/component/Footer/atoms/Mail.tsx
  src/globalStyle/InitStyle.ts
Labels: UI 개선

#44 캘린더 Result 모드 기능 구현
  .gitignore
  src/component/calendar/data/result.ts
  src/component/calendar/organisms/calendar.tsx
  src/util/date.ts
Labels: 리뷰 요청 - 개발 중

#48 로그인 및 코드입력 페이지에서 푸터 고정
  src/component/@share/template/LoginMasterTemplate.tsx
  src/pages/CodeSubmitPage.tsx
Labels: 리뷰 요청 - 개발 완료

#42 Table drag select 구현
  src/component/@share/template/PossibleTimeTemplate.tsx
  src/component/timeBlock/atoms/TimeBlock.tsx
  src/component/timeBlock/molecules/DateList.tsx
  src/component/timeBlock/molecules/SelectAllButton.tsx
  src/component/timeBlock/molecules/SelectDate.tsx
  src/component/timeBlock/molecules/TimeBlockGroup.tsx
  src/component/timeBlock/molecules/TimeList.tsx
  src/store/atoms/TimeBlock/dateListState.ts
  src/store/atoms/TimeBlock/index.ts
  src/store/atoms/TimeBlock/isMouseDownState.ts
  src/store/atoms/TimeBlock/timeListState.ts
  src/store/atoms/TimeBlock/timeTableState.ts
  src/store/atoms/index.ts
  src/util/index.ts
  src/util/touchMoveDrag.ts
Labels: 리뷰 요청 - 개발 완료
